### ISSUE TITLE
Possible to run frida server on Android not rooted?

### ISSUE THREAD

**Issue by Lucstay11** [httptoolkit/frida-js#2]
This program is therefore a Frida client coded in JavaScript instead of Frida-Tools in Python. My question is: would it be possible to create a frida server in nodejs instead of rooting your Android and having to run the frida server as an executable... (In my case bypassing SSL pinning). Because it requires rooting your phone although I admit you need elevated privileges to inject code into a running process (Java class!)

**Comment by pimterry** [comment]
Frida has to run with _complete_ control over the target process you're hooking. For an Android app, there's two ways to do that: by running a standalone Frida server as root (which will host a server allowing control of all apps on the device) or by running [Frida gadget](https://frida.re/docs/gadget/) directly inside a specific target app (which will host a server from inside the app, allowing control of that one app only).

If you don't have root access, you can probably still use Frida Gadget. If you have the app source then that should be fairly easy. If not, you'll need to download the APK, unpack & modify it to inject frida-gadget, and then rebuild, install and run that. All possible, but a bit tricky. The details depend on Frida (not this project) and unfortunately I don't have a full guide to that yet, and I can't help much with the specifics.

Alternatively, you might just want to test on a rooted emulator. Even most of the official emulators (any emulator with an AOSP or 'Google services' OS image, rather than 'Google Play') will provide root access and run Frida with no problems, and every 3rd party emulator I'm aware of will give you root access too.

From the point of view of Frida-JS, it's all basically the same I think - if you can get Frida running in some format, you can point Frida-JS at it and control it remotely from a pure-JS client.

**Comment by Lucstay11** [comment]
Yes I already have an Android root emulator under Android 7.1.1 which runs Frida Server perfectly to bypass SSL pining. Only a lot of Android applications only work under Android > 7. I have a Samsung running Android 12 and I would like to bypass SSL without root access with Frida! Your explanation above seems possible. Do you have any documentation on how to directly inject the Frida server into the target application? And last question, as a JS developer I was wondering why Frida framework is coded in JS and how JS can execute Java code in an application process? Thank you for your valuable response!

**Comment by pimterry** [comment]
> Do you have any documentation on how to directly inject the Frida server into the target application?

No - you'll need to look into the Frida Gadget setup for that yourself. Frida's docs for this are here: https://frida.re/docs/gadget/. If you have questions about that, you should read Frida tutorials or talk to the Frida team, that's kind-of independent of this library really.

> as a JS developer I was wondering why Frida framework is coded in JS and how JS can execute Java code in an application process?

The short answer: Frida isn't coded in JS (most of the core is written in C) but it does contain a JS engine, and it uses that to expose a JS interface to everything it can do. When Frida intercepts a program, it has complete access to its memory and the code that's running. Frida uses this to integrate with various target platform components, in the Java case meaning that it understands how the Java Virtual Machine (JVM) works under the hood, what all its memory means, and how to modify that to do various things. When you call something from JavaScript like `Java.use(className)`, that eventually calls some code written in C to read the process's internal data, and Frida knows how to access these JVM internals to find that classname and read the bytecode for it from the memory it can see, and then give you a JavaScript object containing info it can read from there, and exposing methods which make other changes to that code, or other JVM memory elsewhere that it can access.

For a longer answer, you'll need to dig into Frida itself. If you're interested in that, you can see the various subcomponents linked from https://github.com/frida/frida, and the code that connects Frida's internal JavaScript engine and the JVM specifically is here: https://github.com/frida/frida-java-bridge/

---

I think we've got past the scope of Frida-JS here, so I'm going to close this. If you do have any questions about Frida-JS specifically, do let me know
